name: Build a Container image

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hello-world

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
      - name: Build and push container image
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker build -t $IMAGE_NAME \
            --label "org.opencontainers.image.title=${IMAGE_NAME}" \
            --label "org.opencontainers.image.version=${VERSION}" \
            --label "org.opencontainers.image.source=${{ github.repositoryUrl}}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "build-id=${{ github.run_id }}" .
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
